apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
  - name: centos
    image: centos:latest
    command:  # command will work as ENTRYPOINT in docker
      - "cat"
    args: ["/etc/centos-release"] # args will work as CMD in docker 
  restartPolicy: OnFailure
