apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: frontend
spec:
  containers:
  - name: httpd
    image: ramcloud/httpd_practice:v3
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
