apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nignx
    ports:
      - containerPort: 80
  tolerations:
  - key: app
    operator: "Equal"
    value: "finance"      
    effect: "NoSchedule"