apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    command:
    - /bin/sh
    - -c
    - sleep 30; rm -rf /usr/share/nginx/html; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html
      initialDelaySeconds: 5
      periodSeconds: 5
