apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-http
  labels:
    app: frontend
spec:
  containers:
  - name: nginx-liveness-http
    image: nginx:latest
    ports:
    - containerPort: 80
    command:
    - /bin/sh
    - -c
    - sleep 30; killall yes
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
