apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-tcp
  labels:
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    command:
    - /bin/sh
    - -c
    - sleep 30; killall yes; sleep 600
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
