---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
  selector:
    app: java-app 

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: java-app
spec:
  containers:
  - name: java-app
    image: ramcloud/sample-app:v2
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 20
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 20
    resources: 
      requests: 
        memory: "256Mi"
        cpu: "250m"      
      limits:
        memory: "500Mi"
        cpu: "400m"

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: java-app
spec:
  containers:
  - name: java-app
    image: ramcloud/sample-app:v2
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 3
    resources: 
      requests:  
        memory: "256Mi"
        cpu: "250m"      
      limits:
        memory: "500Mi"
        cpu: "400m"

