apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
  - name: centos-container
    image: centos:latest
    env:
    - name: rel-page-path
      value: /etc/centos-release
    command: ["cat"]
    args: ["$(rel-page-path)"]
  restartPolicy: OnFailure
