# Create secret with below command or follow this document and create secret https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

# kubectl create secret docker-registry <Name- of the secret> \
   --docker-server=ramcloud \
   --docker-username=ramcloud \
   --docker-password=<Password> \
   --docker-email=<Email>


apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: frontend
spec:
  containers:
  - name: httpd
    image: ramcloud/httpd_practice:v3
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
