---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo
spec:
  limits:
  - max:
      cpu: "250m"
    min:
      cpu: "100m"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo
spec:
  limits:
  - max:
      memory: 400Gi
    min:
      memory: 128Mi
    type: Container